In [1]:
import pandas as pd
import numpy as np
# from ydata_profiling import ProfileReport
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

import matplotlib.pyplot as plt
import seaborn as sns

from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

# Explicación: Importante sobre la plantilla

Se tiene que tener en cuenta que este notebook no tiene ningún archivo asociado, ni se carga ningún DataFrame de prueba. Por lo tanto, es una plantilla que no debería ejecutarse como tal, es decir, de este apartado se debería poder identificar que código necesitan y usarlo en el notebook que entregarán en el parcial práctico.

Esta etapa del parcial es en la sala Waira. Deben utilizar los computadores de la sala y conectarse al usuario Examen. En los computadores está disponible Visual Studio Code con Python para editar y ejecutar los notebooks. 
Además, con el fin de que puedan resolver inquietudes de código, tendrán acceso a los siguientes sitios:

    https://scikit-learn.org/
    https://pandas.pydata.org/
    https://imbalanced-learn.org/stable/
    https://numpy.org/
    https://matplotlib.org/
    https://seaborn.pydata.org/
    https://pypi.org/

In [40]:
df = pd.read_csv('Dataset_preparacion_atletica.csv', encoding='utf-8')

In [ ]:

# =========================================================
# Análisis exploratorio y calidad de datos
# =========================================================

In [3]:
data = df.copy()

In [4]:
df.shape

(1000, 13)

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Edad                                       994 non-null    float64
 1   Género                                     991 non-null    str
 2   Tipo de deporte                            986 non-null    str
 3   IMC                                        989 non-null    float64
 4   Horas de entrenamiento por semana          988 non-null    float64
 5   Frecuencia cardíaca en reposo              989 non-null    float64
 6   Ingesta de calorías                        988 non-null    float64
 7   Nivel de experiencia                       987 non-null    str
 8   Frecuencia de competencia                  988 non-null    float64
 9   Indicador de establecimiento de objetivos  990 non-null    str
 10  Puntuación de preparación estratégica      992 non-null    float64
 11  Puntuación de rendimiento                  1000 non-null   float64
 12  log_id                                     1000 non-null   int64
dtypes: float64(8), int64(1), str(4)
memory usage: 131.5 KB

In [6]:
df.describe(include='all')

,Edad,Género,Tipo de deporte,IMC,Horas de entrenamiento por semana,Frecuencia cardíaca en reposo,Ingesta de calorías,Nivel de experiencia,Frecuencia de competencia,Indicador de establecimiento de objetivos,Puntuación de preparación estratégica,Puntuación de rendimiento,log_id
count,994.000000,991,986,989.000000,988.000000,989.000000,988.000000,987,988.000000,990,992.000000,1000.000000,1000.000000
unique,NaN,4,6,NaN,NaN,NaN,NaN,4,NaN,2,NaN,NaN,NaN
top,NaN,Masculino,Ciclismo,NaN,NaN,NaN,NaN,Intermedio,NaN,Sí,NaN,NaN,NaN
freq,NaN,617,182,NaN,NaN,NaN,NaN,353,NaN,600,NaN,NaN,NaN
mean,336.321932,NaN,NaN,23.003061,19.833527,67.700784,3171.146228,NaN,12.156196,NaN,65.071276,82.588758,127131.107000
std,89.011269,NaN,NaN,3.050985,9.098034,13.279323,832.866481,NaN,7.293387,NaN,14.847290,12.841929,71509.545941
min,20.000000,NaN,NaN,15.871890,4.381193,43.977092,1757.476349,NaN,-1.014180,NaN,19.059695,32.211629,86.000000
25%,252.000000,NaN,NaN,20.894943,12.241337,56.098947,2521.711594,NaN,5.958148,NaN,54.719473,73.737318,65272.500000
50%,348.000000,NaN,NaN,23.052422,19.388211,68.073445,3164.124280,NaN,12.178702,NaN,64.543453,83.704262,127463.500000
75%,408.000000,NaN,NaN,25.037110,27.502563,78.573412,3834.560158,NaN,18.840930,NaN,75.876574,92.918808,187957.500000
max,492.000000,NaN,NaN,34.981132,68.990598,114.023258,7225.519216,NaN,25.312736,NaN,100.758629,101.567375,249061.000000

In [7]:
df.describe(include='object')

/var/folders/cp/p5kbj9_s7wv6hvd3xffs7nd40000gn/T/ipykernel_52268/87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,Género,Tipo de deporte,Nivel de experiencia,Indicador de establecimiento de objetivos
count,991,986,987,990
unique,4,6,4,2
top,Masculino,Ciclismo,Intermedio,Sí
freq,617,182,353,600

In [8]:
df.columns

Index(['Edad', 'Género', 'Tipo de deporte', 'IMC',
       'Horas de entrenamiento por semana', 'Frecuencia cardíaca en reposo',
       'Ingesta de calorías', 'Nivel de experiencia',
       'Frecuencia de competencia',
       'Indicador de establecimiento de objetivos',
       'Puntuación de preparación estratégica', 'Puntuación de rendimiento',
       'log_id'],
      dtype='str')

In [9]:
df.isna().sum()

Edad                                          6
Género                                        9
Tipo de deporte                              14
IMC                                          11
Horas de entrenamiento por semana            12
Frecuencia cardíaca en reposo                11
Ingesta de calorías                          12
Nivel de experiencia                         13
Frecuencia de competencia                    12
Indicador de establecimiento de objetivos    10
Puntuación de preparación estratégica         8
Puntuación de rendimiento                     0
log_id                                        0
dtype: int64

# **UNICIDAD**

In [10]:
data.duplicated().sum()

np.int64(4)

In [11]:
data['log_id'].value_counts()

log_id
165207    2
247549    2
93656     2
193996    2
103053    2
         ..
82025     1
213439    1
198256    1
33355     1
137131    1
Name: count, Length: 995, dtype: int64

In [12]:
data[data['log_id'].duplicated(keep=False)]

,Edad,Género,Tipo de deporte,IMC,Horas de entrenamiento por semana,Frecuencia cardíaca en reposo,Ingesta de calorías,Nivel de experiencia,Frecuencia de competencia,Indicador de establecimiento de objetivos,Puntuación de preparación estratégica,Puntuación de rendimiento,log_id
65,432.0,Femenino,Ciclismo,22.744711,16.275209,63.982937,1968.128223,Avanzado,20.656620,No,50.741263,98.274161,165207
144,240.0,F,Ciclismo,17.093331,19.917977,58.524712,3010.648199,Avanzado,19.445792,Sí,59.606272,94.955130,247549
270,408.0,Femenino,Atletismo,34.981132,28.705090,46.999320,2750.530687,Avanzado,21.593026,No,95.325931,65.071071,93656
335,480.0,Masculino,Baloncesto,22.669237,11.335539,79.752030,2263.250266,Avanzado,12.400742,Sí,61.563390,64.099083,193996
347,432.0,Femenino,Ciclismo,22.744711,16.275209,63.982937,1968.128223,Avanzado,20.656620,No,50.741263,98.274161,165207
364,252.0,Masculino,Natación,27.032146,9.658261,46.623510,3646.671190,Intermedio,21.740171,No,71.302106,79.623936,103053
383,480.0,Masculino,Baloncesto,22.669237,11.335539,79.752030,2263.250266,Avanzado,12.400742,Sí,61.563390,64.099083,193996
415,252.0,Masculino,Natación,27.032146,9.658261,46.623510,3646.671190,Intermedio,21.740171,No,71.302106,79.623936,103053
646,408.0,Femenino,Atletismo,34.981132,28.705090,46.999320,2750.530687,Avanzado,21.593026,No,95.325931,65.071071,93656
791,20.0,F,Ciclismo,17.093331,19.917977,58.524712,3010.648199,Avanzado,19.445792,Sí,59.606272,94.955130,247549

In [13]:
data = data.drop_duplicates(subset=["log_id"],keep='last')

In [14]:
data.duplicated().sum()

np.int64(0)

# **CONSISTENCIA**

In [15]:
display(data['Género'].unique())

<ArrowStringArray>
['Masculino', 'Femenino', 'M', 'F', nan]
Length: 5, dtype: str

In [16]:
data.loc[data['Género'] == 'M', 'Género'] = 'Masculino'
data.loc[data['Género'] == 'F', 'Género'] = 'Femenino'

In [18]:
display(data['Género'].unique())

<ArrowStringArray>
['Masculino', 'Femenino', nan]
Length: 3, dtype: str

# **VALIDEZ**

In [19]:
data["Edad"]=data['Edad']/12

In [20]:
data["Edad"]

0      35.0
1      36.0
2      19.0
3      30.0
4      36.0
       ...
995     NaN
996    23.0
997    22.0
998    40.0
999    31.0
Name: Edad, Length: 995, dtype: float64

In [21]:
data[data["IMC"]<=0]

Empty DataFrame
Columns: [Edad, Género, Tipo de deporte, IMC, Horas de entrenamiento por semana, Frecuencia cardíaca en reposo, Ingesta de calorías, Nivel de experiencia, Frecuencia de competencia, Indicador de establecimiento de objetivos, Puntuación de preparación estratégica, Puntuación de rendimiento, log_id]
Index: []

In [22]:
data[data["Frecuencia cardíaca en reposo"]<0]

Empty DataFrame
Columns: [Edad, Género, Tipo de deporte, IMC, Horas de entrenamiento por semana, Frecuencia cardíaca en reposo, Ingesta de calorías, Nivel de experiencia, Frecuencia de competencia, Indicador de establecimiento de objetivos, Puntuación de preparación estratégica, Puntuación de rendimiento, log_id]
Index: []

# **COMPLETITUD**

In [23]:
((data.isnull().sum()/data.shape[0])).sort_values(ascending=False)

Tipo de deporte                              0.014070
Nivel de experiencia                         0.013065
Horas de entrenamiento por semana            0.012060
Ingesta de calorías                          0.012060
Frecuencia de competencia                    0.012060
IMC                                          0.011055
Frecuencia cardíaca en reposo                0.011055
Indicador de establecimiento de objetivos    0.010050
Género                                       0.009045
Puntuación de preparación estratégica        0.008040
Edad                                         0.006030
Puntuación de rendimiento                    0.000000
log_id                                       0.000000
dtype: float64

In [26]:
data = data.dropna(subset=["Indicador de establecimiento de objetivos"])

In [27]:
((data.isnull().sum()/data.shape[0])).sort_values(ascending=False)

Tipo de deporte                              0.014213
Nivel de experiencia                         0.013198
Horas de entrenamiento por semana            0.012183
Ingesta de calorías                          0.012183
Frecuencia de competencia                    0.012183
IMC                                          0.011168
Frecuencia cardíaca en reposo                0.011168
Género                                       0.009137
Puntuación de preparación estratégica        0.008122
Edad                                         0.006091
Indicador de establecimiento de objetivos    0.000000
Puntuación de rendimiento                    0.000000
log_id                                       0.000000
dtype: float64

# **Definir X y Y**

In [28]:
X = data.drop(columns=['Indicador de establecimiento de objetivos',"log_id"])
y = data['Indicador de establecimiento de objetivos']

# **TRAIN/TEST**

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# **PREPROCESAMIENTO**

In [30]:
numeric_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = X_train.select_dtypes(exclude=[np.number]).columns.tolist()

In [31]:
X_train.columns

Index(['Edad', 'Género', 'Tipo de deporte', 'IMC',
       'Horas de entrenamiento por semana', 'Frecuencia cardíaca en reposo',
       'Ingesta de calorías', 'Nivel de experiencia',
       'Frecuencia de competencia', 'Puntuación de preparación estratégica',
       'Puntuación de rendimiento'],
      dtype='str')

In [32]:
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [33]:
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

In [34]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_cols),
        ('cat', categorical_transformer, categorical_cols)
    ]
)

In [35]:
X_train_preparado = preprocessor.fit_transform(X_train)

In [36]:
X_train_df_prep = pd.DataFrame(
    X_train_preparado, 
    columns=preprocessor.get_feature_names_out()
)
display(X_train_df_prep.head())

,num__Edad,num__IMC,num__Horas de entrenamiento por semana,num__Frecuencia cardíaca en reposo,num__Ingesta de calorías,num__Frecuencia de competencia,num__Puntuación de preparación estratégica,num__Puntuación de rendimiento,cat__Género_Femenino,cat__Género_Masculino,cat__Tipo de deporte_Atletismo,cat__Tipo de deporte_Baloncesto,cat__Tipo de deporte_Ciclismo,cat__Tipo de deporte_Fútbol americano,cat__Tipo de deporte_Natación,cat__Tipo de deporte_Tenis,cat__Nivel de experiencia_Avanzado,cat__Nivel de experiencia_Intermedio,cat__Nivel de experiencia_Principiante,cat__Nivel de experiencia_Profesional
0,-0.934339,-0.071345,0.732174,1.583744,-0.560918,0.699133,1.037885,-0.301208,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,-1.343372,-0.346800,0.956012,-1.452954,-0.268819,1.329240,0.738761,1.106091,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.565448,-0.868279,1.285018,0.471427,-0.262592,1.498206,-0.511985,-1.406147,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,-0.388962,0.449835,-1.149315,1.049623,-1.034715,0.983136,-1.391345,-0.823607,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,-1.343372,0.723748,-1.637516,0.730938,0.193663,1.386966,-0.430701,-0.262289,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

#### **PREPARAR X TEST**

In [37]:
X_test_preparado = preprocessor.transform(X_test)

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------